CREATE DATABASE BANCO_SANGUE_DB;
GO

USE BANCO_SANGUE_DB;
GO



CREATE TABLE BS_PESSOA (
	PES_ID INT IDENTITY(1,1) PRIMARY KEY,
	PES_NOME VARCHAR(100) NOT NULL,
	PES_DATANASC DATETIME NOT NULL,
	PES_TIPOSANG CHAR(2) NOT NULL,
	CONSTRAINT CK_BS_PESSOA_PES_TIPOSANG CHECK (PES_TIPOSANG IN('A+', 'A-', 'B+', 'B-', 'O+', 'O-', 'AB+', 'AB-')),
	CONSTRAINT UQ_PES_NOME_PES_DATANASC UNIQUE (PES_NOME, PES_DATANASC)
);


CREATE TABLE BS_DOACAO (
	DOA_ID INT IDENTITY(1,1) PRIMARY KEY,
	DOA_DATA DATETIME NOT NULL,
	DOA_QTDE DECIMAL(18,2) NOT NULL CHECK( DOA_QTDE > 0 AND DOA_QTDE <= 1),
	PES_ID INT NOT NULL,
	CONSTRAINT FK_DOACAO_PESSOA FOREIGN KEY (PES_ID) REFERENCES BS_PESSOA(PES_ID),
	CONSTRAINT CK_DOA_DATA CHECK (DOA_DATA <= GETDATE()),
	CONSTRAINT UQ_DOACAO_PESSOA_DATA UNIQUE (PES_ID, DOA_DATA)
);

CREATE INDEX IDX_BS_DOACAO_PES_ID_DOA_DATA ON BS_DOACAO (PES_ID, DOA_DATA);


